export const UPDATE_FIELD = 'AUTH_UPDATE_FIELD'
export const REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
